services:
  - type: web
    name: spd-wahlkampf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production 