services:
  - type: web
    name: spd-wahlkampf
    plan: starter
    runtime: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: MAIL_USERNAME
        value: Dieter.Meier82@gmail.com
      - key: MAIL_PASSWORD
        value: kewm kjbk hrgh lrgd
      - key: MAIL_DEFAULT_SENDER
        value: Dieter.Meier82@gmail.com